name: icebath
channels:
  - conda-forge
dependencies:
  - datashader
  - h5py
  - holoviews
  - hvplot
  - matplotlib
  - numpy
  - pandas
  - python
  - scipy
  - scikit-learn
  - xarray

  - cartopy
  - descartes
  - fiona
  - geopandas
  - gdal
  - rasterio
  - shapely
  
  - git
  - pip
  - pylint